services:
  - type: web
    name: connect-flow-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn.conf.py 'app:create_app()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: BASE_URL
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_VOICE_NUMBER
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: DEFAULT_ADMIN_EMAIL
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: HOOMAN_ORGANIZATION_ID
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
