"""Add PaymentGateway and update Payment model

Revision ID: d2aaa081bf6e
Revises: 
Create Date: 2026-05-21 15:59:29.580960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2aaa081bf6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_target_results', schema=None) as batch_op:
        batch_op.alter_column('end_reason',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('campaign_targets', schema=None) as batch_op:
        batch_op.alter_column('end_reason',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_campaign_targets_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_targets_external_task_id'), ['external_task_id'], unique=False)
        batch_op.create_unique_constraint(None, ['event_hash'])
        batch_op.create_foreign_key(None, 'module_records', ['record_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'module_records', ['record_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('organization_users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('name')
        batch_op.drop_column('preferences')

    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mfa_method', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_used', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resend_count', sa.Integer(), nullable=True))
        batch_op.alter_column('otp_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index('ix_otp_verifications_email')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('email')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gateway_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gateway_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gateway_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gateway_response', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'payment_gateways', ['gateway_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('gateway_response')
        batch_op.drop_column('gateway_mode')
        batch_op.drop_column('gateway_provider')
        batch_op.drop_column('gateway_name')
        batch_op.drop_column('gateway_id')

    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_otp_verifications_email', ['email'], unique=False)
        batch_op.alter_column('purpose',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('otp_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('resend_count')
        batch_op.drop_column('attempts')
        batch_op.drop_column('is_used')
        batch_op.drop_column('mfa_method')
        batch_op.drop_column('user_id')
        batch_op.drop_column('user_type')

    with op.batch_alter_table('organization_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('delivery_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('campaign_targets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_campaign_targets_external_task_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_targets_conversation_id'))
        batch_op.alter_column('end_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('call_target_results', schema=None) as batch_op:
        batch_op.alter_column('end_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
